version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  run-server:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Set PYTHONPATH
          command: |
            export PYTHONPATH=$PWD/src
      - run:
          name: Export API-KEY
          command: |
            echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" > .env &&
            echo "SERVER_PORT=3000" >> .env &&
            mv .env src
      - run:
          name: Start server
          command: python src/server.py

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_and_test_and_run:
    jobs:
      - run-server
      - test:
          requires:
            - run-server