name: CD Pipeline

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_USER: ${{ vars.HOST_USER }}
  HOST_IP: ${{ vars.HOST_IP }}

on:
  push:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: login to Docker Hub
        run: |
          docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        run: docker build -t turistta .

      - name: tag image
        run: docker tag turistta ${{ vars.DOCKERHUB_USERNAME }}/turistta:latest

      - name: push image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/turistta:latest

  deploy:
    needs: publish_image
    runs-on: ubuntu-latest
    steps:
      - name: Run script in host -> deploy
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -i key.pem -o  StrictHostKeyChecking=no $HOST_USER@$HOST_IP source /root/script.sh
